function parseText(txt){const blocks=txt.split(/\n\s*\n/).map(b=>b.trim()).filter(Boolean);const cards=[];for(const block of blocks){const lines=block.split(/\r?\n/).map(l=>l.trim()).filter(Boolean);if(lines.length>=2){const word=lines[0];const definition=lines.slice(1).join(' ');cards.push({word,definition})}}return cards}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
let allCards=[],currentBatch=[],mcQueue=[],classicQueue=[],batchSize=12,globalQueue=[],state='idle',waitingClassic=false,totalCorrect=0,lastAskedClassicCard=null,lastConfirmedPeriod=null,loadedFileName='',speechEnabled=true,musicEnabled=true,delayedControlsTimer=null
const fileInput=document.getElementById('file'),fileLabel=document.getElementById('fileLabel'),periyotSel=document.getElementById('periyot'),langSel=document.getElementById('lang'),startBtn=document.getElementById('start'),resetBtn=document.getElementById('reset'),progress=document.getElementById('progress'),quiz=document.getElementById('quiz'),definitionEl=document.getElementById('definition'),optionsEl=document.getElementById('options'),typed=document.getElementById('typed'),checkTyped=document.getElementById('checkTyped'),writeArea=document.getElementById('writeArea'),resultEl=document.getElementById('result'),counter=document.getElementById('counter'),continueBtn=document.getElementById('continueBtn'),hintBtn=document.getElementById('hintBtn'),correctBtn=document.getElementById('correctBtn'),dontKnowBtn=document.getElementById('dontKnowBtn'),progressBar=document.getElementById('progressBar'),correctSound=document.getElementById('correctSound'),finishBatchSound=document.getElementById('finishBatchSound'),finishAllSound=document.getElementById('finishAllSound'),switchBox=document.getElementById('switchBox'),speechSwitch=document.getElementById('speechSwitch'),musicSwitch=document.getElementById('musicSwitch')
function updateSwitchBoxLayout(){const v=[...switchBox.children].filter(e=>e.style.display!=='none');v.length===1?switchBox.classList.add('single'):switchBox.classList.remove('single')}
function stopSpeech(){speechSynthesis.cancel()}
function stopAllAudio(){correctSound.pause();finishBatchSound.pause();finishAllSound.pause();correctSound.currentTime=0;finishBatchSound.currentTime=0;finishAllSound.currentTime=0}
function updateSpeechVisibility(){if(langSel.value==='none'){speechSwitch.checked=false;speechEnabled=false;speechSwitch.parentElement.style.display='none'}else{speechSwitch.parentElement.style.display='inline-flex'}updateSwitchBoxLayout()}
speechSwitch.addEventListener('change',()=>{speechEnabled=speechSwitch.checked;if(!speechEnabled)stopSpeech()})
musicSwitch.addEventListener('change',()=>{musicEnabled=musicSwitch.checked;if(!musicEnabled)stopAllAudio()})
langSel.addEventListener('change',()=>{updateSpeechVisibility();if(state==='idle')setIdleStatusText();else setRunningStatusText()})
function playSound(s){if(!musicEnabled)return;s.currentTime=0;s.play()}
function speakWord(word){if(!speechEnabled)return;if(state!=='mc')return;if(langSel.value==='none')return;const lang=langSel.value,utter=new SpeechSynthesisUtterance(word),map={en:'en-US',tr:'tr-TR',de:'de-DE',fr:'fr-FR',es:'es-ES',it:'it-IT',ru:'ru-RU',ja:'ja-JP',ko:'ko-KR',zh:'zh-CN',ar:'ar-SA',pt:'pt-PT',nl:'nl-NL',sv:'sv-SE',pl:'pl-PL',hi:'hi-IN',id:'id-ID',cs:'cs-CZ',el:'el-GR',he:'he-IL',th:'th-TH',vi:'vi-VN'};utter.lang=map[lang]||'en-US';stopSpeech();speechSynthesis.speak(utter)}
function getPeriod(){return parseInt(periyotSel.value,10)}
function getDefaultPeriodByCount(c){return c<=30?6:c<=60?12:24}
function applyDefaultPeriodByCount(c){const p=getDefaultPeriodByCount(c);periyotSel.value=String(p);lastConfirmedPeriod=p}
function resetProgressBar(){totalCorrect=0;progressBar.style.width='0%'}
function setFileInputVisible(v){fileLabel.style.display=v?'inline-flex':'none'}
function setStudyControlsVisible(v){periyotSel.style.display=v?'inline-block':'none';langSel.style.display=v?'inline-block':'none';startBtn.style.display=v?'inline-block':'none';resetBtn.style.display=v?'inline-block':'none'}
function setStartButtonLabel(){startBtn.textContent=state==='idle'?'Start':'Restart'}
function langName(){return langSel.options[langSel.selectedIndex]?.text||'None'}
function getLoadedPrefix(){return loadedFileName?loadedFileName+': ':''}
function setIdleStatusText(){progress.textContent=allCards.length?getLoadedPrefix()+allCards.length+' cards loaded. Select a period and a language then click "Start" (Period: '+getPeriod()+', Language: '+langName()+').':'Please upload your txt file.'}
function setRunningStatusText(){progress.textContent=getLoadedPrefix()+allCards.length+' cards loaded (Period: '+getPeriod()+', Language: '+langName()+').' }
function updateProgressBar(){const t=allCards.length*2;progressBar.style.width=(totalCorrect/t*100)+'%'}
function showDelayedControls(){if(delayedControlsTimer)clearTimeout(delayedControlsTimer);if(state!=='classic'||classicQueue.length===0)return;hintBtn.style.display='none';dontKnowBtn.style.display='none';hintBtn.style.opacity='0';dontKnowBtn.style.opacity='0';const t=1600;delayedControlsTimer=setTimeout(()=>{if(state==='classic'&&!waitingClassic&&classicQueue.length>0){hintBtn.style.display='inline-block';dontKnowBtn.style.display='inline-block';setTimeout(()=>{hintBtn.style.opacity='1';dontKnowBtn.style.opacity='1'},50)}},t)}
function hardReset(){if(delayedControlsTimer)clearTimeout(delayedControlsTimer);stopSpeech();stopAllAudio();resetProgressBar();allCards=[];currentBatch=[];mcQueue=[];classicQueue=[];globalQueue=[];state='idle';waitingClassic=false;totalCorrect=0;lastAskedClassicCard=null;lastConfirmedPeriod=null;loadedFileName='';speechEnabled=true;musicEnabled=true;speechSwitch.checked=true;musicSwitch.checked=true;quiz.style.display='none';optionsEl.innerHTML='';writeArea.style.display='none';hintBtn.style.display='none';dontKnowBtn.style.display='none';correctBtn.style.display='none';continueBtn.style.display='none';typed.value='';resultEl.textContent='';counter.textContent='';definitionEl.textContent='';fileInput.value='';periyotSel.value='12';langSel.value='en';switchBox.style.display='none';updateSpeechVisibility();setFileInputVisible(true);setStudyControlsVisible(false);setStartButtonLabel();setIdleStatusText();updateProgressBar();langSel.disabled=false;updateSwitchBoxLayout()}
function beginStudy(){if(!allCards.length){progress.textContent='Please upload your txt file first.';return}stopSpeech();resetProgressBar();shuffle(allCards);batchSize=getPeriod();globalQueue=allCards.slice();state='mc';waitingClassic=false;lastAskedClassicCard=null;lastConfirmedPeriod=batchSize;quiz.style.display='block';setFileInputVisible(false);setStudyControlsVisible(true);setStartButtonLabel();setRunningStatusText();switchBox.style.display='flex';updateSpeechVisibility();langSel.disabled=true;prepareNextBatch();updateProgressBar()}
fileInput.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;loadedFileName=f.name;const r=new FileReader();r.onload=ev=>{allCards=parseText(ev.target.result);if(allCards.length){shuffle(allCards);applyDefaultPeriodByCount(allCards.length);setFileInputVisible(false);setStudyControlsVisible(true);setIdleStatusText();setStartButtonLabel()}else{loadedFileName='';setFileInputVisible(true);setStudyControlsVisible(false);progress.textContent='File is empty or invalid.'}};r.readAsText(f,'utf-8')})
startBtn.addEventListener('click',()=>beginStudy())
resetBtn.addEventListener('click',()=>hardReset())
periyotSel.addEventListener('change',()=>{const v=getPeriod();if(state==='idle'){lastConfirmedPeriod=v;setIdleStatusText();return}const ok=confirm('Changing the period will restart your session. Are you sure?');if(ok)beginStudy();else{if(lastConfirmedPeriod!=null)periyotSel.value=String(lastConfirmedPeriod);setRunningStatusText()}})
function prepareNextBatch(){if(delayedControlsTimer)clearTimeout(delayedControlsTimer);if(globalQueue.length===0){playSound(finishAllSound);progress.textContent=getLoadedPrefix()+'All ('+batchSize+') periods ('+allCards.length+' cards) completed.';definitionEl.textContent='Finished';optionsEl.innerHTML='';writeArea.style.display='none';hintBtn.style.display='none';dontKnowBtn.style.display='none';correctBtn.style.display='none';continueBtn.style.display='none';resultEl.textContent='';counter.textContent='';if(langSel.value!=='none')speechSwitch.parentElement.style.display='inline-flex';setStartButtonLabel();langSel.disabled=true;updateSwitchBoxLayout();return}currentBatch=globalQueue.splice(0,batchSize);mcQueue=currentBatch.slice();shuffle(mcQueue);classicQueue=currentBatch.slice();state='mc';waitingClassic=false;lastAskedClassicCard=null;speechSwitch.parentElement.style.display=langSel.value==='none'?'none':'inline-flex';updateSwitchBoxLayout();renderMC()}
function renderMC(){if(mcQueue.length===0){state='classic';speechSwitch.parentElement.style.display='none';updateSwitchBoxLayout();renderClassic();return}const c=mcQueue[0];definitionEl.textContent=c.word;speakWord(c.word);optionsEl.innerHTML='';const o=shuffle(allCards.map(x=>x.definition).filter(d=>d!==c.definition)).slice(0,3);const ch=shuffle([c.definition,...o]);for(const x of ch){const b=document.createElement('button');b.className='opt-btn';b.textContent=x;b.onclick=()=>handleMCAnswer(b,x,c);optionsEl.appendChild(b)}writeArea.style.display='none';typed.value='';resultEl.textContent='MC: Please select one of the options.';hintBtn.style.display='none';dontKnowBtn.style.display='none';correctBtn.style.display='none';continueBtn.style.display='none';counter.textContent='MC: '+(currentBatch.indexOf(c)+1)+'/'+currentBatch.length;updateSwitchBoxLayout()}
function handleMCAnswer(btn,ans,c){for(const b of optionsEl.children)b.disabled=true;if(ans===c.definition){stopSpeech();btn.classList.add('correct');resultEl.textContent='Correct!';playSound(correctSound);totalCorrect++;updateProgressBar();mcQueue.shift();setTimeout(()=>renderMC(),500)}else{btn.classList.add('wrong');resultEl.textContent='Wrong. Correct: '+c.definition;mcQueue.shift();mcQueue.push(c);continueBtn.style.display='inline-block';waitingClassic=true}}
continueBtn.addEventListener('click',()=>{if(waitingClassic){waitingClassic=false;continueBtn.style.display='none';if(state==='classic'){writeArea.style.display='flex';renderClassic()}else renderMC()}})
function renderClassic(){if(delayedControlsTimer)clearTimeout(delayedControlsTimer);if(classicQueue.length===0){if(globalQueue.length>0){playSound(finishBatchSound);prepareNextBatch();return}progress.textContent=getLoadedPrefix()+'All ('+batchSize+') periods ('+allCards.length+' cards) completed.';definitionEl.textContent='Finished';optionsEl.innerHTML='';writeArea.style.display='none';hintBtn.style.display='none';dontKnowBtn.style.display='none';correctBtn.style.display='none';continueBtn.style.display='none';resultEl.textContent='';counter.textContent='';playSound(finishAllSound);if(langSel.value!=='none')speechSwitch.parentElement.style.display='inline-flex';setStartButtonLabel();langSel.disabled=true;updateSwitchBoxLayout();return}const c=classicQueue[0];definitionEl.textContent=c.definition;optionsEl.innerHTML='';writeArea.style.display='flex';typed.value='';resultEl.textContent='Classic: Type your written answer.';counter.textContent='Classic: '+(currentBatch.indexOf(c)+1)+'/'+currentBatch.length;hintBtn.style.display='none';dontKnowBtn.style.display='none';correctBtn.style.display='none';continueBtn.style.display='none';showDelayedControls();updateSwitchBoxLayout()}
checkTyped.addEventListener('click',()=>{if(state!=='classic'||waitingClassic)return;const a=typed.value.trim();if(!a){resultEl.textContent='Please type something.';return}const c=classicQueue.shift();const isLastClassicInBatch=classicQueue.length===0;const isLastBatch=globalQueue.length===0;if(a.toLowerCase()===c.word.toLowerCase()){stopSpeech();resultEl.textContent='Correct!';totalCorrect++;updateProgressBar();lastAskedClassicCard=null;waitingClassic=false;if(!isLastClassicInBatch){playSound(correctSound)}if(isLastClassicInBatch&&!isLastBatch){playSound(finishBatchSound)}if(isLastClassicInBatch&&isLastBatch){playSound(finishAllSound)}setTimeout(()=>renderClassic(),400)}else{resultEl.textContent='Wrong. Correct: '+c.word;classicQueue.push(c);lastAskedClassicCard=c;waitingClassic=true;continueBtn.style.display='inline-block';correctBtn.style.display='inline-block';hintBtn.style.display='none';dontKnowBtn.style.display='none';writeArea.style.display='none'}})
hintBtn.addEventListener('click',()=>{if(classicQueue.length>0&&!waitingClassic){typed.value=classicQueue[0].word.slice(0,2)}})
dontKnowBtn.addEventListener('click',()=>{if(classicQueue.length>0&&!waitingClassic){const c=classicQueue.shift();typed.value=c.word;resultEl.textContent='Correct: '+c.word;classicQueue.push(c);lastAskedClassicCard=c;writeArea.style.display='none';hintBtn.style.display='none';correctBtn.style.display='none';dontKnowBtn.style.display='none';continueBtn.style.display='inline-block';waitingClassic=true}})
correctBtn.addEventListener('click',()=>{if(classicQueue.length>0&&lastAskedClassicCard){const i=classicQueue.indexOf(lastAskedClassicCard);if(i>-1)classicQueue.splice(i,1);totalCorrect++;updateProgressBar();const isLastClassicInBatch=classicQueue.length===0;const isLastBatch=globalQueue.length===0;if(!isLastClassicInBatch){playSound(correctSound)}if(isLastClassicInBatch&&!isLastBatch){playSound(finishBatchSound)}if(isLastClassicInBatch&&isLastBatch){playSound(finishAllSound)}lastAskedClassicCard=null;waitingClassic=false;continueBtn.style.display='none';correctBtn.style.display='none';writeArea.style.display='flex';renderClassic()}else if(classicQueue.length>0){classicQueue.shift();waitingClassic=false;continueBtn.style.display='none';correctBtn.style.display='none';renderClassic()}})
typed.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();checkTyped.click()}})
hardReset()
